cec15_test : cec15_test_func.h ecr_iml.c evaluation_count_iml.c main.c record_result_iml.c rp_iml.c cec15_test_func.c jkiss.h jkiss.c
	g++ -o cec15_test -lm -fPIC ecr_iml.c evaluation_count_iml.c main.c record_result_iml.c rp_iml.c cec15_test_func.c jkiss.c

clean:
	rm cec15_test
